---
# tasks file for nutanix_provisioner

- name: Check if host already exist
  command: ping -c1 -w2 {{ item.ip }}
  delegate_to: localhost
  ignore_errors: true
  register: ping_result
  with_items: "{{vm_configuration }}"
  changed_when: False

- name: success
  debug: var=ping_result.stdout
  when: ping_result is succeeded

- name: failed
  debug: var=ping_result.stdout
  when: ping_result is failed

- name: Skip creation for this host when success
  meta: end_play
  when: ping_result is succeeded

- name: test name
  set_fact:
    cluster_name: "NTNX-{{ item.cluster|upper }}-01"
    subnet_name: "{{ item.subnet }}"
  with_items: 
    - "{{ vm_configuration }}"


- import_tasks: get_session_cookie.yml
- import_tasks: get_cluster_uuids.yml
- import_tasks: get_subnet_uuids.yml
- import_tasks: get_image_uuids.yml
- import_tasks: define_uuids_from_names.yml
- import_tasks: provision_vm.yml
